algoritmo "Media1a5"
// Função : Mostra a média entre cinco números
// Autor :  Milena Rubik Peres
// Data : 14/04/2022
// Seção de Declarações 
var
asoma: inteiro
amedia: inteiro //não preciso usar real já que a média de 1 a 5 é um inteiro
inicio
// Seção de Comandos
asoma<-1+2+3+4+5
amedia<- asoma/5
escreval("A soma dos números 1,2,3,4 e 5 é",asoma)
escreva("A média dos números 1,2,3,4 e 5 é",amedia)
fimalgoritmo
