algoritmo "MultiplicaInput2"
// Função : Mostra a multiplicação entre 10 números informados pelo usuário
// Autor :  Milena Rubik Peres
// Data : 14/04/2022
// Seção de Declarações 
var
multiplica,i,num: inteiro
inicio
// Seção de Comandos
i<-1
multiplica<-1
enquanto i <= 3 faca
escreval("Digite um número inteiro")
leia(num)
multiplica<-multiplica*num
i<-i+1
fimenquanto

escreval("A multiplicação dos números digitados é",multiplica)

fimalgoritmo
