algoritmo "MultiplicaInput1"
// Função : Mostra a multiplicação entre 10 números informados pelo usuário
// Autor :  Milena Rubik Peres
// Data : 14/04/2022
// Seção de Declarações 
var
multiplica,resultado,i,num: inteiro
inicio
// Seção de Comandos
i<-1
multiplica<-1
para i de 1 ate 10 faca
escreval("Digite um número inteiro")
leia(num)
multiplica<-multiplica*num
fimpara

escreval("A multiplicação dos números digitados é",multiplica)

fimalgoritmo
